import { WordEntry } from '../types';

export const VOCABULARY: WordEntry[] = [
  // Pagina 1
  { word: "aanstonds", definition: "onmiddellijk, meteen" },
  { word: "abject", definition: "verachtelijk, afkeurenswaardig (bv. een … mening)" },
  { word: "abusievelijk", definition: "onjuist, verkeerd, per abuis" },
  { word: "acquisitie", definition: "aanwinst/aankoop, werving (bv. van klanten, personeel)" },
  { word: "actedepresence", definition: "(geven) aanwezig zijn" },
  { word: "acuut", definition: "dringend, urgent" },
  { word: "adrem", definition: "raak, gevat, snel en met humor (bv. een ad remme reactive)" },
  { word: "adept", definition: "volgeling, aanhanger" },
  { word: "aforisme", definition: "korte, pittige spreuk; levenswijsheid" },
  { word: "agitatie", definition: "nerveuze opwinding" },
  { word: "aldus", definition: "zo, op deze manier" },
  { word: "allooi", definition: "waarde, kwaliteit, kaliber (bv. van bedenkelijk … zijn)" },
  { word: "altruisme", definition: "onzelfzuchtigheid (↔ egoïsme)" },
  { word: "alvorens", definition: "(te) (vw.) voordat" },
  { word: "ambivalent", definition: "tegenstrijdig, dubbel (bv. … gevoelens)" },
  { word: "ambulant", definition: "niet aan bed gebonden of zonder vaste plaats, mobiel" },
  { word: "ampel", definition: "(bn.) uitvoerig, omstandig (bv. na … overweging)" },
  { word: "antropocentrisch", definition: "de mens centraal stellend (↔theocentrisch)" },
  { word: "apathisch", definition: "ongevoelig voor emoties, onverschillig" },

  // Pagina 2
  { word: "areaal", definition: "oppervlakte, terrein (bv. woning…, landbouw…)" },
  { word: "ascetisch", definition: "sober, simpel en strikt, zichzelf onthoudend van genot" },
  { word: "assimileren", definition: "opgaan in, zich aanpassen aan" },
  { word: "attitude", definition: "Instelling, psychische houding" },
  { word: "banaal", definition: "alledaags, afgezaagd" },
  { word: "behoudens", definition: "uitgezonderd (bv. … een paar kleine wijzigingen)" },
  { word: "belendend", definition: "aangrenzend (bv. een … perceel)" },
  { word: "benevens", definition: "alsook" },
  { word: "bestendigen", definition: "laten voortduren, van kracht doen blijven" },
  { word: "blamage", definition: "afgang, schaamtevolle gebeurtenis" },
  { word: "blase", definition: "zo verwend dat je niet meer kunt genieten" },
  { word: "bonafide", definition: "betrouwbaar" },
  { word: "bonnefooi", definition: "(op de) op goed geluk" },
  { word: "cachet", definition: "een eigen en stijlvol karakter, onderscheidend kenmerk" },
  { word: "categorisch", definition: "stellig, zonder twijfel (bv. iets … ontkennen)" },
  { word: "catharsis", definition: "zuivering van de ziel, loutering" },
  { word: "cesuur", definition: "grenspunt tussen voldoende en onvoldoende, breuk" },
  { word: "chargeren", definition: "overdrijven" },

  // Pagina 3
  { word: "chicaneren", definition: "moeilijkheden zoeken in, muggenziften, vitten" },
  { word: "clandestien", definition: "(bn.) geheim, bij wet verboden" },
  { word: "clementie", definition: "toegeeflijkheid, mildheid, genade" },
  { word: "coherent", definition: "logisch samenhangend" },
  { word: "cohesie", definition: "samenhang" },
  { word: "coincidentie", definition: "een toevallige samenloop van omstandigheden, toeval" },
  { word: "compatibel", definition: "verenigbaar, geschikt voor/passend bij" },
  { word: "compromitteren", definition: "in een negatief daglicht stellen, in opspraak brengen" },
  { word: "concessie", definition: "gedeeltelijke toegeving, tegemoetkoming" },
  { word: "conclaaf", definition: "besloten vergadering, overleg in besloten kring" },
  { word: "confisqueren", definition: "in beslag nemen" },
  { word: "conscientieus", definition: "zorgvuldig, nauwgezet" },
  { word: "contingent", definition: "aandeel, bijdrage" },
  { word: "corpulent", definition: "zwaarlijvig, dik" },
  { word: "corrumperen", definition: "slechter maken, bederven, verloederen" },
  { word: "coulant", definition: "inschikkelijk, toegevend, tolerant, flexibel" },
  { word: "culmineren", definition: "uitlopen op, zijn hoogtepunt vinden in" },
  { word: "curieus", definition: "merkwaardig, vreemd, opmerkelijk" },
  { word: "dd", definition: "d.d. (de dato): van de datum, daterend van" },

  // Pagina 4
  { word: "daaromtrent", definition: "wat datgene betreft, daarover" },
  { word: "debiteur", definition: "schuldenaar, iemand die in de schuld staat" },
  { word: "decimeren", definition: "uitdunnen, sterk verminderen in aantal" },
  { word: "declameren", definition: "met gevoel voordragen" },
  { word: "decoderen", definition: "ontcijferen" },
  { word: "decorum", definition: "uiterlijke waardigheid, deftigheid, fatsoen" },
  { word: "deemoedig", definition: "nederig" },
  { word: "deformeren", definition: "vervormen (vaak negatief), misvormen" },
  { word: "demagogie", definition: "misleiden van een volk door leugens te vertellen" },
  { word: "demonisch", definition: "duivels, diabolisch" },
  { word: "deprivatie", definition: "van essentiële zaken beroven/onthouden" },
  { word: "desperaat", definition: "wanhopig, radeloos" },
  { word: "despoot", definition: "dictator, alleenheerser, heerszuchtig persoon" },
  { word: "determineren", definition: "bepalen" },
  { word: "deviant", definition: "(bn.) afwijkend" },
  { word: "dienaangaande", definition: "daarover, daaromtrent" },
  { word: "diffuus", definition: "vaag, verstrooid, onscherp" },
  { word: "dilettant", definition: "amateur, zonder deskundige grondige kennis" },
  { word: "dispensatie", definition: "vrijstelling, ontheffing" },

  // Pagina 5
  { word: "dividend", definition: "deel van de winst dat naar aandeelhouders gaat" },
  { word: "doorvorsen", definition: "grondig onderzoeken, doorgronden" },
  { word: "doubleren", definition: "blijven zitten, een leerjaar overdoen" },
  { word: "eclectisch", definition: "het beste selecterend uit verschillende bronnen" },
  { word: "epicentrum", definition: "plaats waar een aardbeving het heftigst is, middelpunt" },
  { word: "eruditie", definition: "deskundigheid, geleerdheid" },
  { word: "esoterisch", definition: "geheim, enkel voor ingewijden" },
  { word: "esthetisch", definition: "m.b.t. de waarneming en waardering van het schone" },
  { word: "exponent", definition: "vertegenwoordiger, representant van een groep" },
  { word: "faitaccompli", definition: "voldongen feit, wat niet meer ongedaan kan worden" },
  { word: "farce", definition: "dwaze grap, scherts, schijnvertoning, klucht" },
  { word: "facsimile", definition: "kopie, reproductie, nauwkeurige nabootsing" },
  { word: "feilbaar", definition: "imperfect, die zich kan vergissen" },
  { word: "flegmatiek", definition: "onverstoorbaar kalm, koel, laconiek" },
  { word: "forfait", definition: "bepaald vast bedrag" },

  // Pagina 6
  { word: "fragiel", definition: "kwetsbaar, breekbaar" },
  { word: "frivool", definition: "lichtzinnig (oppervlakkig), wuft, vrolijk" },
  { word: "fulmineren", definition: "hevig uitvallen, schelden op, foeteren tegen" },
  { word: "futiliteit", definition: "kleinigheid, onbenulligheid" },
  { word: "gebrouilleerd", definition: "in onmin (bv. wij zijn gebrouilleerd)" },
  { word: "gedegen", definition: "grondig, degelijk, goed doordacht" },
  { word: "geenszins", definition: "allesbehalve, absoluut niet" },
  { word: "geexalteerd", definition: "overdreven opgewonden, in vervoering" },
  { word: "gelasten", definition: "(ww.) (juridisch) bevelen, verordenen" },
  { word: "generlei", definition: "geen enkele" },
  { word: "geraffineerd", definition: "verfijnd (bv. een … smaak)" },
  { word: "gespeendvan", definition: "zonder, iets missend, ver verwijderd van" },
  { word: "gezapig", definition: "gemoedelijk" },
  { word: "gezeglijk", definition: "gehoorzaam, inschikkelijk" },
  { word: "gezwind", definition: "snel, gehaast, haastig" },
  { word: "grotesk", definition: "vreemd, buitensporig, lachwekkend" },
  { word: "hausse", definition: "stijging, flinke toename van" },
  { word: "hautain", definition: "arrogant, hooghartig" },
  { word: "hedonisme", definition: "leer waarin genot centraal staat" },
  { word: "hegemonie", definition: "overwicht (van een staat/partij)" },

  // Pagina 7
  { word: "heimelijk", definition: "stiekem, verborgen, in het geheim" },
  { word: "heremiet", definition: "kluizenaar, iemand die teruggetrokken leeft" },
  { word: "hetze", definition: "laster/haatcampagne" },
  { word: "hybris", definition: "hoogmoed, overdreven trots" },
  { word: "hypochonder", definition: "iemand die denkt dat hij allerlei ziektes heeft" },
  { word: "imposant", definition: "indrukwekkend" },
  { word: "incasu", definition: "in casu (i.c.): in dit geval" },
  { word: "incubatietijd", definition: "tijd tussen besmetting en uitbraak van een ziekte" },
  { word: "indolent", definition: "traag, laks, lusteloos" },
  { word: "ingeval", definition: "indien, als, in het geval dat" },
  { word: "inscriptie", definition: "gravure, tekst in hard materiaal gebeiteld" },
  { word: "insinuatie", definition: "impliciete indirecte/bedekte beschuldiging" },
  { word: "insubordinatie", definition: "ongehoorzaamheid tegenover een meerdere" },
  { word: "interpelleren", definition: "ondervragen, om opheldering vragen" },
  { word: "interrumperen", definition: "onderbreken" },
  { word: "intrigant", definition: "iemand die stookt tussen partijen" },
  { word: "inzage", definition: "het iets inzien ter kennisneming" },
  { word: "jegens", definition: "tegenover, ten aanzien van" },
  { word: "jeremiade", definition: "uiting van pijn of leed, jammerklacht" },

  // Pagina 8
  { word: "jobstijding", definition: "onheilstijding, mededeling van iets ergs" },
  { word: "joviaal", definition: "opgewekt en vriendelijk, warm" },
  { word: "judasstreek", definition: "verraderlijke streek" },
  { word: "jurisprudentie", definition: "toegepaste rechtspraak, rechtsopvatting" },
  { word: "kapittelen", definition: "ernstig de les lezen, streng berispen" },
  { word: "katheder", definition: "spreekgestoelte" },
  { word: "kenschetsen", definition: "kenmerken, karakteriseren" },
  { word: "kleinood", definition: "voorwerp dat klein maar waardevol is" },
  { word: "kleptomaan", definition: "iemand die dwangmatig steelt" },
  { word: "koeterwaals", definition: "wat niet te verstaan of te begrijpen is" },
  { word: "krachtens", definition: "volgens, op gezag van" },
  { word: "laconiek", definition: "uiterst kalm, ongevoelig" },
  { word: "lamentabel", definition: "ellendig, erbarmelijk" },
  { word: "lankmoedig", definition: "geduldig, veel verdragend" },
  { word: "lasteren", definition: "kwaad van iemand spreken dat niet waar is" },
  { word: "leemte", definition: "lacune, tekortkoming, iets wat ontbreekt" },
  { word: "legaat", definition: "bepaling in testament die erfenis vastlegt" },
  { word: "lethargisch", definition: "ongevoelig, gevoelloos, passief" },

  // Pagina 9
  { word: "liquide", definition: "direct beschikbaar (bv. liquide middelen)" },
  { word: "liturgie", definition: "godsdienstplechtigheid, ceremoniële dienst" },
  { word: "logenstraffen", definition: "het doen blijken dat iets niet waar is" },
  { word: "lucide", definition: "verlicht, verhelderend, helder van geest" },
  { word: "lumineus", definition: "schitterend (bv. een lumineus idee)" },
  { word: "lustrum", definition: "periode van vijf jaar" },
  { word: "macaber", definition: "griezelig, luguber t.o.v. de dood" },
  { word: "magistraal", definition: "(bn.) meesterlijk (bv. een … boek)" },
  { word: "malafide", definition: "(bn.) onbetrouwbaar" },
  { word: "malaise", definition: "crisis, sombere toestand, onprettig gevoel" },
  { word: "mandaat", definition: "volmacht, opdracht" },
  { word: "marchanderen", definition: "over de prijs of voorwaarden handelen" },
  { word: "mastodont", definition: "groot gevaarte (bv. mastodont van een boom)" },
  { word: "merites", definition: "verdiensten" },
  { word: "mijnerzijds", definition: "mijns inziens, van mijn kant" },
  { word: "naarstig", definition: "met veel inspanning, ijverig" },
  { word: "navrant", definition: "hartverscheurend" },
  { word: "negorij", definition: "gehucht, klein dorp of kleine stad" },
  { word: "nestor", definition: "oudste van een groep met de meeste ervaring" },
  { word: "netelig", definition: "ingewikkeld, lastig (bv. een … probleem)" },

  // Pagina 10
  { word: "nijverheid", definition: "industrie" },
  { word: "nopens", definition: "betreffende, over" },
  { word: "notoir", definition: "berucht (bv. een notoire dief)" },
  { word: "novum", definition: "iets wat volledig nieuw is" },
  { word: "obstinaat", definition: "koppig, eigenwijs" },
  { word: "occult", definition: "aan tovenarij gerelateerd, verborgen, geheim" },
  { word: "oecumene", definition: "nastreven van eenheid tussen christenen" },
  { word: "ofschoon", definition: "hoewel" },
  { word: "onbestendig", definition: "veranderlijk, niet constant" },
  { word: "onbillijk", definition: "niet schappelijk, onredelijk, onrechtvaardig" },
  { word: "ontstentenis", definition: "afwezigheid (bv. bij … van de voorzitter)" },
  { word: "ontwaren", definition: "beginnen te zien, gewaarworden" },
  { word: "opportuun", definition: "van pas komend, geschikt moment" },
  { word: "ostentatief", definition: "met als doel de aandacht te trekken" },
  { word: "outillage", definition: "uitrusting, materieel" },
  { word: "paraaf", definition: "verkorte handtekening (initialen)" },

  // Pagina 11
  { word: "parabel", definition: "symbolisch verhaal over een morele kwestie" },
  { word: "pathetisch", definition: "hartstochtelijk, medelijden opwekkend" },
  { word: "pauper", definition: "een arm, minder bedeeld persoon" },
  { word: "pedant", definition: "hoogdravend, verwaand, zelfingenomen" },
  { word: "penibel", definition: "pijnlijk, benauwend, hachelijk" },
  { word: "perfide", definition: "verraderlijk (bv. die uitleg is …)" },
  { word: "persiflage", definition: "namaak/imitatie om belachelijk te maken" },
  { word: "pertinent", definition: "relevant (bv. dat is een … opmerking)" },
  { word: "pieteit", definition: "liefde en eerbied (bv. uit … met de nabestaanden)" },
  { word: "plebejer", definition: "iemand uit een lagere sociale klasse" },
  { word: "plegen", definition: "de gewoonte hebben om iets te doen" },
  { word: "plenair", definition: "voltallig, compleet vergaderend" },
  { word: "polemiek", definition: "schriftelijke discussie, pennenstrijd" },
  { word: "pontificaal", definition: "plechtig, nadrukkelijk" },
  { word: "postuum", definition: "na iemands overlijden" },
  { word: "prangend", definition: "dringend (bv. een … vraag)" },
  { word: "precair", definition: "zorgwekkend, delicaat" },

  // Pagina 12
  { word: "pregnant", definition: "betekenisvol, kernachtig geformuleerd" },
  { word: "prematuur", definition: "(te) vroegtijdig, voorbarig" },
  { word: "primaat", definition: "oppergezag, wat het belangrijkst is" },
  { word: "proforma", definition: "voor de vorm, voor de schijn" },
  { word: "probaat", definition: "effectief, beproefd (bv. een probaat middel)" },
  { word: "profaan", definition: "werelds, niet-religieus, spottend" },
  { word: "professie", definition: "beroep" },
  { word: "puriteins", definition: "strenggelovig" },
  { word: "queeste", definition: "lange zoektocht" },
  { word: "raffinement", definition: "finesse, verfijndheid" },
  { word: "ramsj", definition: "handel in boeken tegen lage prijzen" },
  { word: "recalcitrant", definition: "opstandig, dwarsbomend" },
  { word: "recidivist", definition: "iemand die opnieuw een misdaad pleegt" },
  { word: "regressief", definition: "teruggaand naar een eerder stadium" },
  { word: "rehabiliteren", definition: "herstellen van eer en goede naam" },
  { word: "relaas", definition: "lang gedetailleerd verhaal, betoog" },
  { word: "relict", definition: "overblijfsel" },

  // Pagina 13
  { word: "rendabel", definition: "winstgevend" },
  { word: "respijt", definition: "uitstel, onderbreking" },
  { word: "ressentiment", definition: "wrok, haat door gevoel van onrecht" },
  { word: "resumeren", definition: "samenvatten" },
  { word: "saillant", definition: "opvallend (bv. een … detail)" },
  { word: "schielijk", definition: "vlug, plotseling" },
  { word: "seponeren", definition: "niet vervolgen (van een rechtszaak)" },
  { word: "snob", definition: "iemand die zich probeert te onderscheiden" },
  { word: "sofist", definition: "iemand die een drogreden aanvoert" },
  { word: "solvabiliteit", definition: "vermogen om aan betalingen te voldoen" },
  { word: "sonoor", definition: "helder en aangenaam klinkend" },
  { word: "specimen", definition: "voorbeeld, exemplaar, proefmonster" },
  { word: "sponde", definition: "(archaïsch) bed" },
  { word: "stigmatiseren", definition: "brandmerken, negatief afschilderen" },
  { word: "stoicijns", definition: "onverstoorbaar" },
  { word: "sublimeren", definition: "verbeteren, naar een hoger niveau tillen" },

  // Pagina 14
  { word: "successievelijk", definition: "achtereenvolgens" },
  { word: "suprematie", definition: "oppergezag" },
  { word: "surplus", definition: "extra hoeveelheid boven wat nodig is" },
  { word: "tanen", definition: "glans verliezen, verbleken, afnemen" },
  { word: "tantaluskwelling", definition: "kwelling door onbereikbaar begeerde" },
  { word: "tarten", definition: "uitdagen, trotseren" },
  { word: "tendentieus", definition: "gekleurd, misleidend" },
  { word: "teneur", definition: "strekking, hoofdgedachte" },
  { word: "tertiair", definition: "derde" },
  { word: "timbre", definition: "klankkleur van stem of instrument" },
  { word: "transcendent", definition: "uitstijgend boven een grens, onvatbaar" },
  { word: "trojka", definition: "leiderschap van drie personen" },
  { word: "tycoon", definition: "rijke en invloedrijke zakenman, magnaat" },
  { word: "uitspansel", definition: "hemelboog, hemelgewelf" },

  // Pagina 15
  { word: "unaniem", definition: "eenstemmig, iedereen is het eens" },
  { word: "urgent", definition: "zeer dringend" },
  { word: "utopie", definition: "onbereikbare ideale wereld" },
  { word: "vacant", definition: "openstaand, niet bezet" },
  { word: "vadsig", definition: "dik en lui" },
  { word: "valide", definition: "gegrond, (rechts)geldig" },
  { word: "veinzen", definition: "doen alsof" },
  { word: "vergaren", definition: "opdoen, verzamelen" },
  { word: "verloochenen", definition: "niet willen erkennen" },
  { word: "verscheiden", definition: "overlijden (ww.)" },
  { word: "vilein", definition: "vals, gemeen" },
  { word: "viriel", definition: "mannelijk" },
  { word: "voornemens", definition: "van plan zijn iets te doen" },
  { word: "voorts", definition: "verder, vervolgens" },
  { word: "vrucht", definition: "(met vrucht) met succes" },
  { word: "weemoedig", definition: "droevig, verdrietig" },
  { word: "wijlen", definition: "overleden (bn.)" },
  { word: "wraken", definition: "verwerpen, afkeuren" },
  { word: "zinnebeeldig", definition: "symbolisch" },
  { word: "zinnelijk", definition: "gericht op zintuiglijk genot" },

  // Pagina 16
  { word: "zulks", definition: "zoiets, een dergelijk iets" },
  { word: "zwanenzang", definition: "het laatste werk van een kunstenaar" },
  { word: "zwelgen", definition: "volledig opgaan in, volop genieten van" },
  { word: "aberratie", definition: "gebreken, afwijking" },
  { word: "abominabel", definition: "afschuwelijk, heel slecht" },
  { word: "absoluut", definition: "tegenovergestelde van relatief" },
  { word: "abstract", definition: "tegenovergestelde van concreet" },
  { word: "accidenteel", definition: "per ongeluk, toevallig" },
  { word: "accuratesse", definition: "nauwkeurigheid, stiptheid" },
  { word: "additioneel", definition: "toegevoegd, extra" },
  { word: "adequaat", definition: "gepast, geschikt" },
  { word: "analoog", definition: "vergelijkbaar, niet digitaal" },
  { word: "apert", definition: "opvallend, heel duidelijk" },
  { word: "appendix", definition: "bijlage, aanhangsel" },
  { word: "arbitrair", definition: "willekeurig" },
  { word: "artificieel", definition: "kunstmatig" },
  { word: "catastrofaal", definition: "rampzalig" },
  { word: "categoriaal", definition: "indeling in vaste categorieën" },
  { word: "causaal", definition: "oorzakelijk" },

  // Pagina 17
  { word: "chronisch", definition: "langdurig" },
  { word: "cognitief", definition: "mentaal, verstandelijk" },
  { word: "competent", definition: "bekwaam" },
  { word: "concreet", definition: "tastbaar, duidelijk" },
  { word: "consecutief", definition: "opeenvolgend" },
  { word: "consistent", definition: "in lijn liggen van, samenhangend" },
  { word: "contradictie", definition: "tegenstrijdigheid" },
  { word: "convergent", definition: "naar elkaar toe bewegend" },
  { word: "convergentie", definition: "het naar elkaar toe groeien" },
  { word: "corpus", definition: "verzameling teksten of data" },
  { word: "correlatie", definition: "samenhang" },
  { word: "cruciaal", definition: "doorslaggevend" },
  { word: "daar", definition: "omdat" },
  { word: "data", definition: "gegevens" },
  { word: "deduceren", definition: "logisch afleiden" },
  { word: "derhalve", definition: "daarom, bijgevolg" },
  { word: "descriptief", definition: "beschrijvend" },
  { word: "digitaal", definition: "tegenovergestelde van analoog" },
  { word: "discrepantie", definition: "verschil, afwijking" },
  { word: "divergent", definition: "uiteenlopend" },
  { word: "divergentie", definition: "het uiteenlopen" },
  { word: "doch", definition: "echter, nochtans" },
  { word: "dominant", definition: "overheersend" },
  { word: "dynamisch", definition: "bewegelijk, veranderlijk" },
  { word: "enige", definition: "een beetje" },
  { word: "equivalent", definition: "komt overeen, gelijke waarde" },

  // Pagina 18
  { word: "evenwel", definition: "echter, toch" },
  { word: "exhaustief", definition: "volledig, er ontbreekt niks" },
  { word: "expliciet", definition: "uitdrukkelijk, helder geformuleerd" },
  { word: "extrapoleren", definition: "uitbreiden, doortrekken" },
  { word: "facultatief", definition: "niet verplicht" },
  { word: "falsificeren", definition: "aantonen dat het fout is" },
  { word: "focussen", definition: "concentreren, richten" },
  { word: "frequent", definition: "vaak voorkomend" },
  { word: "gelieve", definition: "alsjeblieft" },
  { word: "geluimd", definition: "gestemd, gezind" },
  { word: "generaliseren", definition: "veralgemenen" },
  { word: "geschieden", definition: "gebeuren, voorvallen" },
  { word: "gewis", definition: "zeker, beslist" },
  { word: "grijzeliteratuur", definition: "info buiten traditionele kanalen" },
  { word: "heterogeen", definition: "ongelijksoortig" },
  { word: "hetwelk", definition: "betrekkelijk voornaamwoord" },
  { word: "homogeen", definition: "op elkaar lijkend, gelijksoortig" },
  { word: "honoreren", definition: "selecteren, waarderen" },
  { word: "implementeren", definition: "toepassen, uitvoeren" },
  { word: "impliciet", definition: "onuitgesproken, begrepen" },
  { word: "incentive", definition: "beloning, prikkel" },
  { word: "incidenteel", definition: "zelden, sporadisch" },
  { word: "indicatie", definition: "aanwijzing" },
  { word: "innovatief", definition: "vernieuwend" },
  { word: "instrueren", definition: "instructies geven" },

  // Pagina 19
  { word: "interactie", definition: "wisselwerking" },
  { word: "interdisciplinair", definition: "tussen verschillende wetenschappen" },
  { word: "lacune", definition: "leemte, ontbrekend deel" },
  { word: "latent", definition: "onzichtbaar, verborgen" },
  { word: "legitiem", definition: "terecht, gegrond" },
  { word: "lineair", definition: "rechtlijnig" },
  { word: "methodologie", definition: "methode van onderzoek" },
  { word: "mondiaal", definition: "over de hele wereld" },
  { word: "nopen", definition: "dwingen, verplichten" },
  { word: "objectief", definition: "feitelijk, zonder oordeel" },
  { word: "omissie", definition: "nalatigheid, verzuim" },
  { word: "onderbouwen", definition: "motiveren, bewijzen" },
  { word: "onderhavig", definition: "huidig, actueel" },
  { word: "ondervangen", definition: "tenietdoen, verhelpen" },
  { word: "oneigenlijk", definition: "niet juist, misbruik" },
  { word: "ongefundeerd", definition: "ongegrond, zonder basis" },
  { word: "paradoxaal", definition: "tegenstrijdig" },
  { word: "participeren", definition: "deelnemen" },
  { word: "pendant", definition: "tegenhanger" },
  { word: "plausibel", definition: "geloofwaardig, aannemelijk" },
  { word: "pogen", definition: "trachten, proberen" },
  { word: "poneren", definition: "beweren, stellen" },
  { word: "populariseren", definition: "toegankelijk maken" },
  { word: "pragmatisch", definition: "praktisch ingesteld" },
  { word: "premisse", definition: "uitgangspunt, veronderstelling" },

  // Pagina 20
  { word: "prescriptief", definition: "met bepaalde normen, voorschrijvend" },
  { word: "preventief", definition: "uit voorzorg" },
  { word: "rectificeren", definition: "fouten rechtzetten" },
  { word: "redigeren", definition: "tekst aanpassen en verbeteren" },
  { word: "redundant", definition: "overbodig" },
  { word: "referentiekader", definition: "geheel van factoren" },
  { word: "referenties", definition: "bronnen, bronvermelding" },
  { word: "refereren", definition: "verwijzen naar" },
  { word: "relateren", definition: "linken aan" },
  { word: "relatief", definition: "betrekkelijk" },
  { word: "repercussie", definition: "onaangename gevolgen" },
  { word: "resterend", definition: "overblijvend" },
  { word: "restricties", definition: "beperkingen, regels" },
  { word: "reviseren", definition: "herzien, nakijken" },
  { word: "schier", definition: "bijna, haast" },
  { word: "sedert", definition: "sinds" },
  { word: "setting", definition: "omgeving, context" },
  { word: "simuleren", definition: "nabootsen" },
  { word: "simultaan", definition: "gelijktijdig" },
  { word: "speculeren", definition: "verwachtingen formuleren" },
  { word: "statisch", definition: "niet bewegend" },
  { word: "subjectief", definition: "persoonlijk, bevooroordeeld" },
  { word: "substantieel", definition: "duidelijk, wezenlijk" },
  { word: "substitutie", definition: "vervanging" },
  { word: "teneinde", definition: "om, opdat" },
  { word: "terugkoppelen", definition: "feedback geven, teruggaan" },

  // Pagina 21
  { word: "thans", definition: "nu, momenteel" },
  { word: "these", definition: "stelling" },
  { word: "triviaal", definition: "alledaags, gewoon" },
  { word: "verifieren", definition: "checken, controleren" },
  { word: "welke", definition: "betrekkelijk voornaamwoord" }
];